trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'ae44d01b-cfe4-414c-8251-3867ea59ec20'
  containerRegistry: 'advancedsoftware.azurecr.io'
  tag: '$(Build.BuildId)'

  # Define repositories for services
  authServiceImageRepository: 'authentication-service'
  postServiceImageRepository: 'post-service'

  # Dockerfile paths
  authServiceDockerfilePath: '$(Build.SourcesDirectory)/Back-End/authentication-service/Dockerfile'
  postServiceDockerfilePath: '$(Build.SourcesDirectory)/Back-End/post-service/Dockerfile'

stages:
- stage: Build
  displayName: Build and Push Stage
  jobs:
  - job: BuildAuthService
    displayName: Build Authentication Service
    pool:
      name: 'Default'
    steps:
    - task: Docker@2
      displayName: Build and Push Authentication Service Image
      inputs:
        command: buildAndPush
        repository: $(authServiceImageRepository)
        dockerfile: $(authServiceDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

  - job: BuildPostService
    displayName: Build Post Service
    pool:
      name: 'Default'
    steps:
    - task: Docker@2
      displayName: Build and Push Post Service Image
      inputs:
        command: buildAndPush
        repository: $(postServiceImageRepository)
        dockerfile: $(postServiceDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
