# Docker
# Build and push multiple images to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection
  dockerRegistryServiceConnection: '7147f71d-fe16-4654-b741-fb238a729eca'
  containerRegistry: 'advancedsoftware.azurecr.io'

  # Repositories
  authImageRepository: 'authentication-service'
  postImageRepository: 'post-service'

  # Dockerfile paths
  authDockerfilePath: '$(Build.SourcesDirectory)/Back-End/authentication-service/Dockerfile'
  postDockerfilePath: '$(Build.SourcesDirectory)/Back-End/post-service/Dockerfile'

  # Tagging format
  tag: '$(Build.BuildId)'  

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build and Push Docker Images
    pool:
      name: default
    steps:
    - task: Docker@2
      displayName: Build and push authentication-service
      inputs:
        command: buildAndPush
        repository: $(containerRegistry)/$(authImageRepository)  
        dockerfile: $(authDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

    - task: Docker@2
      displayName: Build and push post-service
      inputs:
        command: buildAndPush
        repository: $(containerRegistry)/$(postImageRepository)  
        dockerfile: $(postDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
