trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection
  dockerRegistryServiceConnection: '7147f71d-fe16-4654-b741-fb238a729eca'

  # Kubernetes Cluster details
  aksClusterName: 'AKS-2'
  aksResourceGroup: 'AdvancedSoftware'

  # Tagging format
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push Docker Images
  jobs:
  - job: Build
    displayName: Build and Push Docker Images
    pool:
      name: default
    steps:
    - task: Docker@2
      displayName: Build and push authentication-service
      inputs:
        command: buildAndPush
        repository: 'authentication-service'
        dockerfile: $(Build.SourcesDirectory)/Back-End/authentication-service/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

    - task: Docker@2
      displayName: Build and push post-service
      inputs:
        command: buildAndPush
        repository: 'post-service'
        dockerfile: $(Build.SourcesDirectory)/Back-End/post-service/Dockerfile
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

    - task: Docker@2
      displayName: Build and push vue3-frontend
      inputs:
        command: buildAndPush
        repository: 'vue3-frontend'
        dockerfile: $(Build.SourcesDirectory)/Front-End/Dockerfile 
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest

# Deploy stage
- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool:
      name: default
    steps:
    - task: AzureCLI@2
      displayName: 'Set up kubectl'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksClusterName) --overwrite-existing

    # - task: AzureCLI@2
    #   displayName: 'Create NGINX ConfigMap'
    #   inputs:
    #     azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
    #     scriptType: bash
    #     scriptLocation: inlineScript
    #     inlineScript: |
    #       kubectl apply -f $(Build.SourcesDirectory)/Back-End/nginx/nginx-configmap.yaml

    - task: AzureCLI@2
      displayName: 'Deploy authentication-service to AKS'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f $(Build.SourcesDirectory)/Back-End/authentication-service/authentication-service-deployment.yaml
          
    - task: AzureCLI@2
      displayName: 'Deploy post-service to AKS'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f $(Build.SourcesDirectory)/Back-End/post-service/post-service-deployment.yaml
  
    - task: AzureCLI@2
      displayName: 'Deploy authentication-service HPA'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f $(Build.SourcesDirectory)/Back-End/authentication-service/authentication-service-hpa.yaml

    - task: AzureCLI@2
      displayName: 'Deploy post-service HPA'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f $(Build.SourcesDirectory)/Back-End/post-service/post-service-hpa.yaml  

    # - task: AzureCLI@2
    #   displayName: 'Deploy NGINX Gateway to AKS'
    #   inputs:
    #     azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
    #     scriptType: bash
    #     scriptLocation: inlineScript
    #     inlineScript: |
    #       kubectl apply -f $(Build.SourcesDirectory)/Back-End/nginx/nginx-deployment.yaml
    #       kubectl apply -f $(Build.SourcesDirectory)/Back-End/nginx/nginx-gateway-service.yaml

    - task: AzureCLI@2
      displayName: 'Deploy Traefik IngressRoutes'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f $(Build.SourcesDirectory)/Back-End/treafik/traefik-ingress.yaml
          kubectl apply -f $(Build.SourcesDirectory)/Back-End/treafik/traefik-service.yaml


    - task: AzureCLI@2
      displayName: 'Deploy vue3-frontend to AKS'
      inputs:
        azureSubscription: 'Azure for Students(50ccea06-45f9-4d03-928c-45d883ef83ff)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f $(Build.SourcesDirectory)/Front-End/vue3-frontend-deployment.yaml
