apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: advancedsoftware.azurecr.io/post-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "local"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "advanced-software.mysql.database.azure.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "post_db"
            - name: DB_USERNAME
              value: "mees"
            - name: DB_PASSWORD
              value: "Advanced_Software1"
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
