services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - authentication-service
      - post-service
    networks:
      - laravel_network

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    container_name: AuthenticationService
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./authentication-service:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: authDB-central
      DB_PORT: 3306
      DB_DATABASE: central_db
      DB_USERNAME: mees
      DB_PASSWORD: Advanced_Software1
      JWT_SECRET: p7Q5vf48CsX6KQvHe8j5D4EpHXmO0jTuNdYBkwYFmdvr9fFjsoki5RbUdXItaFi3

    networks:
      - laravel_network
    ports:
      - "8001:8000"

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile.local
    container_name: PostService
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./post-service:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: central

      DB_HOST: postDB-central
      DB_PORT: 3306
      DB_DATABASE: central_db
      DB_USERNAME: mees
      DB_PASSWORD: Advanced_Software1

      DB_SHARD1_HOST: postDB-shard1
      DB_SHARD1_DATABASE: shard1_db
      DB_SHARD1_USERNAME: mees
      DB_SHARD1_PASSWORD: Advanced_Software1

      DB_SHARD2_HOST: postDB-shard2
      DB_SHARD2_DATABASE: shard2_db
      DB_SHARD2_USERNAME: mees
      DB_SHARD2_PASSWORD: Advanced_Software1
      JWT_SECRET: p7Q5vf48CsX6KQvHe8j5D4EpHXmO0jTuNdYBkwYFmdvr9fFjsoki5RbUdXItaFi3
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - laravel_network
    ports:
      - "8002:8000"
    depends_on:
      - postDB-central
      - postDB-shard1
      - postDB-shard2
      - redis


  authDB-central:
    image: mysql:8.0
    container_name: authDB_central
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: central_db
      MYSQL_USER: mees
      MYSQL_PASSWORD: Advanced_Software1
    ports:
      - "3310:3306"
    volumes:
      - auth_central_db_data:/var/lib/mysql
    networks:
      - laravel_network


  postDB-central:
    image: mysql:8.0
    container_name: postDB_central
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: central_db
      MYSQL_USER: mees
      MYSQL_PASSWORD: Advanced_Software1
    ports:
      - "3307:3306"
    volumes:
      - post_central_db_data:/var/lib/mysql
    networks:
      - laravel_network

  postDB-shard1:
    image: mysql:8.0
    container_name: postDB_shard1
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shard1_db
      MYSQL_USER: mees
      MYSQL_PASSWORD: Advanced_Software1
    ports:
      - "3308:3306"
    volumes:
      - post_shard1_db_data:/var/lib/mysql
    networks:
      - laravel_network

  postDB-shard2:
    image: mysql:8.0
    container_name: postDB_shard2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shard2_db
      MYSQL_USER: mees
      MYSQL_PASSWORD: Advanced_Software1
    ports:
      - "3309:3306"
    volumes:
      - post_shard2_db_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network




volumes:
  post_central_db_data:
  auth_central_db_data:
  post_shard1_db_data:
  post_shard2_db_data:

networks:
  laravel_network:
    driver: bridge

