services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - authentication-service
      - post-service
    networks:
      - laravel_network

  authentication-service:
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    container_name: AuthenticationService
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./authentication-service:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: advanced-software.mysql.database.azure.com
      DB_PORT: 3306
      DB_DATABASE: authentication_db
      DB_USERNAME: mees
      DB_PASSWORD: Advanced_Software1
    networks:
      - laravel_network
    ports:
      - "8001:8000"

  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: PostService
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./post-service:/var/www/html
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: advanced-software.mysql.database.azure.com
      DB_PORT: 3306
      DB_DATABASE: post_db
      DB_USERNAME: mees
      DB_PASSWORD: Advanced_Software1
    networks:
      - laravel_network
    ports:
      - "8002:8000"

networks:
  laravel_network:
    driver: bridge

