apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  nginx.conf: |
    events {
        worker_connections 1024;  # You can adjust this based on your needs
    }

    http {
        upstream authentication_service {
            server authentication-service:80;
        }

        upstream post_service {
            server post-service:80;
        }

        server {
            listen 80;

            location /api/auth/ {
                rewrite ^/api/auth/(.*)$ /api/auth/$1 break;
                proxy_pass http://authentication_service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /api/posts/ {
                rewrite ^/api/posts/(.*)$ /api/posts/$1 break;
                proxy_pass http://post_service/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location / {
                return 404;
            }
        }
    }
